### ISSUE TITLE
Hard Coded Thirty

### ISSUE THREAD

**Issue by lloy0076** [TendoPayPlugins/tendopay-wp#11]
https://github.com/TendoPayPlugins/tendopay-wp/blob/31abdc3193440dafb6f32a1e75e8b1380fa3eb8e/src/TendoPay/API/Endpoint_Caller.php#L136

There's something distinctly "wrong" about this but I can't put my finger on it...

```
{
  "aud": "2",
  "jti": "LONG_ID",
  "iat": 1536154066,
  "nbf": 1536154066,
  "exp": 1536758866,
  "sub": "",
  "scopes": []
}
```

The one to "really" watch out for is `exp` - if the token is before that (I think it's seconds in epoch).

If epoch is past that, it's expired.

**Comment by robklo** [comment]
do you mean that part?

`$current_timestamp - 30`

I want to refresh the bearer token a bit earlier than it really needs in order not hit the issue of the expired bearer token in the middle of the payment processing.

On the other hand, it will check the expiration timestamp with every call, so it might be overengineered, but does it hurts us in any way?

**Comment by lloy0076** [comment]
Yes, but then it will hit the expired token `$current_timestamp - 30` before hand; it's like this: "If the probability > 0 and the number of attempts may be infinite, it **will** happen with a probability of 1".

**Comment by robklo** [comment]
You are right and I wasn't clear. I'm totally aware it still CAN happen, but the probability is much lesser.

With every API call (we have two or three calls "chained" before redirecting), we check if the bearer token is still valid. So it's only a matter of the time between checking the bearer exp date and receiving and reading the request by API server. It's is much more probable that the call will fail just because when we were checking the exp date it was the last second, and when the API server received the request it was just after the bearer token expired. If we invalidate it a bit earlier, this is very unlikely it will ever happen (although not impossible)
